### ISSUE TITLE
Add workflow permissions for Clients

### ISSUE THREAD

**Issue by ericpoe** [happybottoms/coverd#103]
The client workflow needs permissions set for each transition in the workflow.

See #86 for the transition permissions to set.

**Comment by ericpoe** [comment]
@akoebbe In #86 we show the three roles that can do anything with a client transition: "author," "partner," and "administrator." How do these 3 roles map to our existing roles?

Also, client roles are completely dependent upon the whims of the sysadmin of this application, so we are not guaranteed that any roles by any name will exist at all times when using this application. Should we make whatever the equivalent of "author," "partner," and "administrator" be immutable (as a separate ticket)?

**Comment by akoebbe** [comment]
I'm sorry for missing this.

Author and partner can be seen as the same. This is an anti-pattern from Drupal permissions stuff. We always had to make sure the author (user) and the assigned partner (partner record) were the same. It was super confusing and has caused a bunch of visibility problems. We just want to make sure the `$user->getActivePartner()` is the same as the client.

> Also, client roles are completely dependent upon the whims of the sysadmin of this application, so we are not guaranteed that any roles by any name will exist at all times when using this application.

I'm not sure I understand what you mean. Are you talking about `ROLE_*` roles?

**Comment by ericpoe** [comment]
@akoebbe yes, the `ROLE_*` roles.

I think at this point, though, the dynamic `ROLE_*` roles are external to this workflow.

**Comment by ericpoe** [comment]
Closed by #161
