### ISSUE TITLE
Add Voters for Supplier Entities

### ISSUE THREAD

**Issue by akoebbe** [happybottoms/coverd#114]
We need a Voter for the Supplier entities. There are two roles: `Supplier::ROLE_VIEW` and `Supplier::ROLE_EDIT` that need to be checked before showing or editing a supplier. I think the routes guards are already in place, so this should be pretty simple.

**Comment by uplyft** [comment]
Alrighty. Seems to be working when I remove Supplier user roles from the volunteer group. I'm not exactly sure if it's behaving precisely as you envisioned however. Want to give it a try and let me know, @akoebbe?

**Comment by akoebbe** [comment]
Closed by #116
