### ISSUE TITLE
Partner Voter

### ISSUE THREAD

**Issue by akoebbe** [happybottoms/coverd#117]
We need a voter to limit access to view and edit on Partners. Standard edit all, view all, manage own roles apply. We will also need to check the user's active partner in the "Manage own" role case. This is similar to the client voter.

**Comment by uplyft** [comment]
@akoebbe I've committed the bulk of it now, but unsure if we need to let the user without `ROLE_PARTNER_VIEW_ALL` show a list of all partners.
