### ISSUE TITLE
Update API Route Security to use Annotations and Proper Roles

### ISSUE THREAD

**Issue by akoebbe** [happybottoms/coverd#126]
We currently have the scaffolding for route security in security.yaml, but I think we should move that in to controller method annotations.

We should follow https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/security.html to add permissions via annotations. For example for GroupsController.php, we should do...

```php
use App\Entity\Group;
use App\Transformers\GroupTransformer;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted; // <-- Need this for annotations
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * Class GroupController
 * @package App\Controller
 *
 * @Route(path="/api/groups")
 */
class GroupController extends BaseController
{
    protected $defaultEntityName = Group::class;

    /**
     * Get a list of Groups
     *
     * @Route(path="", methods={"GET"})
     * @IsGranted({"ROLE_ADMIN"}) // <-- This can be a list of roles
     *
     * @return JsonResponse
     */
    public function index(Request $request)
    {
        $groups = $this->getRepository()->findAll();

        return $this->serialize($request, $groups);
    }

```

**Comment by uplyft** [comment]
Thanks @akoebbe... Could you please check out the commit linked above and let me know how it looks to you? I'm unsure about of all of it.

**Comment by akoebbe** [comment]
This is an awesome start. A few things...

1. When doing multi-line annotations you should still inlcude a `*` character on new lines and indent a more. For example...
    ```php
    /**
     *
     * @IsGranted({
     *    "ROLE_ADMIN",
     *    "ROLE_ADJUSTMENT_ORDER_EDIT",
     * })
     *
     */
    ```
2. In the example above (`AdjustmentOrderController::update()`) we don't need the `ROLE_ADMIN` since the admin group already has the `ROLE_ADJUSTMENT_ORDER_EDIT` role. It's a little confusing that they are called "Roles" when they are really abilities.

Does that make sense?

**Comment by uplyft** [comment]
> Does that make sense?

Yes, thanks @akoebbe!
