### ISSUE TITLE
Banks should be able to merge duplicate clients

### ISSUE THREAD

**Issue by akoebbe** [happybottoms/coverd#129]
If there are duplicated clients a bank user (not a partner) should be able to select 

# Terminology

- Source Client - This is the client that will be deactivated at the end of the process
- Target Client - This is the client that will remain active and assume all associated order line items of the source client.

# Current Process

1. User looks at the detail view of a client and can click the merge tab to start the process
    ![image](https://user-images.githubusercontent.com/1044465/86873968-0c7ee100-c0a5-11ea-8243-7f9a99d02578.png)
2. The user is given a search to find the other client they want to merge this client with
    ![image](https://user-images.githubusercontent.com/1044465/86874171-75feef80-c0a5-11ea-9027-c076c4b2a71f.png)
3. The user is shown a diff of the clients to verify they have the right clients selected.
    ![image](https://user-images.githubusercontent.com/1044465/86874471-0a695200-c0a6-11ea-8a89-3b1d7271de16.png)
4. The original client is merged in to the searched client and all of the associated line items are move over to the target client.

# New Process

The new process does not need to adhere to the old UX. In fact, we can model this on the way we currently merge suppliers. 

![image](https://user-images.githubusercontent.com/1044465/86875015-30dbbd00-c0a7-11ea-93a9-bdc8f68186d1.png)

So in this case the process would be...
1. Search for the duplicate clients
2. Check the boxes
3. Choose "Merge Clients" from the bulk operations menu
4. A popup will appear with a drop down to select the target client (the rest will be deactivated)
5. A summary of the changes are shown to the user before confirming.

This is just a suggestion and does not have to be the way we do this, but we already have an example of this to work from if we want.

**Comment by uplyft** [comment]
I like your idea of modeling this after the suppliers, @akoebbe!

**Comment by uplyft** [comment]
@akoebbe I'm a little unclear on what exactly a client merge entails. By what logic do we reconcile the data from one to the other? Or are we simply deactivating all but the selected client? Thanks in advance!

**Comment by akoebbe** [comment]
@uplyft I'll have to look at the old code to see if I'm merging any of the fields to the target client, but I'm pretty sure it's not. The thing that needs to happen is all of the PartnerOrderLineItems that are associated with the clients that will be deactivated should be reassigned to the target client. Does that make sense. When the merge is all done, the target client should have all of the line items and the deactivated clients should have none.

One additional thing is a field on the Client entity that references another client so that we know which client the deactivated one was merged in to. We can make that a separate issue if that seems best.

**Comment by akoebbe** [comment]
@uplyft I've confirmed in the Drupal code all we are doing in the actual merge method is

1. moving the line items over to the target client
2. transitioning the status of the others to inactive
3. setting the "merged to" field on the inactive client to reference the target client
4. setting the "merged at" field to `now` (I don't think we need this since the status transitions are logged)
