### ISSUE TITLE
Client Listing: Hide UUID column and make the client name the link to the detail view of the client

### ISSUE THREAD

**Issue by akoebbe** [happybottoms/coverd#136]
Right now we are using GUIDs for Client identifiers, but they take up a log of room on the list view. Should we show a truncated version, hide it, or use another shorter obfuscated identifier generator?

![image](https://user-images.githubusercontent.com/1044465/86996946-8f21a200-c172-11ea-8cac-d8436dab9dba.png)

**Comment by akoebbe** [comment]
Possible idea. On other project I worked on we used loostro/cryptomute which does format preserving encryption of the original ID. So if we zero padded the DB id field to, say 10 digits, then what we would get back a unique encrypted 10-digit ID from cryptomute, without collisions.

**Comment by uplyft** [comment]
@akoebbe Is there any other use for a shorter uid that we will accomplish by creating it for this? Is there a reason we need to display these ids at all? Could we instead remove this column and link the whole row to the client detail?

**Comment by akoebbe** [comment]
That's a good question. Then only reason I was thinking of smaller client IDs is when I've had to reference the clients with HappyBottoms, but the more I think about it, I don't think that's really been needed. Mostly they've just referenced the clients by name.

I think we can just hide the UUID and make the client name the link to the detail record. I'll update this issue description.
