### ISSUE TITLE
Client list does not sort by name

### ISSUE THREAD

**Issue by uplyft** [happybottoms/coverd#151]
After #136, when you click the column heading "Name" at /#/clients, the table is not sorted by name. The sorting feedback icon does appear to work as expected.

I have tried setting the `sortField` property within the `columns` array at ClientList.vue, but I can't tell that it has any effect at all. I'm curious to know if it's because this column uses `__slot:link` and is thereby different from the other columns.

**Comment by ffeliks** [comment]
I took an attempt at this issue: https://github.com/happybottoms/coverd/pull/214
