### ISSUE TITLE
Get phpstan to run in travis-ci

### ISSUE THREAD

**Issue by ericpoe** [happybottoms/coverd#18]
When enabling phpstan in travis-ci, phpstan will throw errors related to not finding the phpunit-bridge autoloader.

> `Compile Error: PHPStan\Command\CommandHelper::PHPStan\Command\{closure}():   
>   Failed opening required '/home/travis/build/happybottoms/coverd/bin/.phpunit/phpunit-7.5/vendor/autoload.php' (include_path='.:/home/travis/.phpenv/versions/7.3.9/share/pear')`

Because phpstan is set up to also scan the `Tests` directory, it needs to know how to read the tests extended from various PHPUnit classes.

**Comment by smrhoney** [comment]
I submitted a pull request for this issue.

**Comment by ericpoe** [comment]
Thanks @smrhoney !
