### ISSUE TITLE
Error when editing a client

### ISSUE THREAD

**Issue by akoebbe** [happybottoms/coverd#181]
The following error message shows up when clicking on a client in the client list to edit it.

![image](https://user-images.githubusercontent.com/1044465/93932603-139dae80-fce6-11ea-8ed5-d884bfce83b8.png)

**Comment by akoebbe** [comment]
@ericpoe any clues on this?

**Comment by akoebbe** [comment]
Oh. This is only happening when logged in as a partner. Probably permission related.

**Comment by akoebbe** [comment]
Yes. If you have `CLIENT_MANAGE_OWN` it will error, but if you have `CLIENT_EDIT_ALL` it will work fine.

**Comment by ericpoe** [comment]
What should the resolution be on this? Should we gracefully error when `ROLE_CLIENT_MANAGER_OWN`?

**Comment by akoebbe** [comment]
Well if this client is linked to the logged-in user's active partner, it should let them edit it. Basically this should have let me (a partner) edit my client.

**Comment by akoebbe** [comment]
To clarify. Log in as a partner user. Go to the client list and try to bring one of your own clients up to edit. That's where this is failing.

**Comment by ericpoe** [comment]
Resolved by #208
