### ISSUE TITLE
Do custom Vue component references right

### ISSUE THREAD

**Issue by akoebbe** [happybottoms/coverd#2]
Before I knew the right way to do things, the custom components were registered globally in the `app.js` and with a `hb-` prefix. This causes a great deal of shame. :-(

We need to change all of those to proper custom component references. Instead of registering those globally, we should include them in `.vue` files that use them.

See the use of `SupplierMerge` in `SupplierList.vue` for a good example of the correct way:
- https://github.com/happybottoms/coverd/blob/master/assets/js/views/supplier/SupplierList.vue#L116
- https://github.com/happybottoms/coverd/blob/master/assets/js/views/supplier/SupplierList.vue#L124
- https://github.com/happybottoms/coverd/blob/master/assets/js/views/supplier/SupplierList.vue#L127

**Comment by ericpoe** [comment]
Closed by #34 

Thanks @calbear47 !
