### ISSUE TITLE
Create the Client Entity

### ISSUE THREAD

**Issue by akoebbe** [happybottoms/coverd#3]
The `Client` entity represents the final recipient of the product. This would equate to the child receiving the diapers for a diaper bank.

Since every bank will be different regarding what they want to track about the client, we won't need a ton of hardcoded properties on the entity. Most of the fields will be handled through the EAV system (custom fields).

Major things to consider:
- Clients must have a GUID for their externally referenced IDs. Something like a short (random?) hash.
- Client records must be encrypted (the base encryption system will be in another effort)

Both of these things are for PII security.

For right now let's get the following properties on the Client entity

- First Name
- Last Name

(anything else?

**Comment by ericpoe** [comment]
For my education and any others looking at this issue:
* [PII Privacy Act](https://www.gsa.gov/reference/gsa-privacy-program/rules-and-policies-protecting-pii-privacy-act)
