### ISSUE TITLE
Address security alerts

### ISSUE THREAD

**Issue by akoebbe** [happybottoms/coverd#5]
GitHub is reporting a handful of security alerts in our yarn.lock file. We should upgrade the relevant packages to more secure versions.

**Comment by lesliesmith** [comment]
Merged master into each of the github created branches: 

dependabot/npm_and_yarn/axios-0.18.1
dependabot/npm_and_yarn/eslint-utils-1.4.2
dependabot/npm_and_yarn/lodash-4.17.13

Tested the dependencies with yarn install and yarn watch processes and then checked the application functionality.  All the screens seemed to function as well as they did in the master branch.

**Comment by akoebbe** [comment]
All merged in. Thank you @lesliesmith!
