### ISSUE TITLE
Partner Logins

### ISSUE THREAD

**Issue by akoebbe** [happybottoms/coverd#80]
We need a way to add login users associated with many partners. It's possible that one user could manage many partner locations so it's important we don't assign users to only one department.

My gut says we set up a many-to-many relationship between Partners and PartnerUser (new subclass of User). Then we add a UI tab to the partner screen to at least view the users. And a user edit screen that will allow for multiple partner assignments.

Let's start here and I'll add another ticket for permissions.

**Comment by akoebbe** [comment]
@uplyft Let me know when you have your latest changes checking in and I'll get cracking on this one.

**Comment by uplyft** [comment]
@akoebbe Thanks for your help! Check it out now and let me know what you think? I am hoping I got the right things reverted (original Users and Partners), and as you know the rest of it is sort of half-baked.

**Comment by akoebbe** [comment]
Closed by #92
