### ISSUE TITLE
Throw nice error when attempting to delete a product category that is in-use

### ISSUE THREAD

**Issue by ericpoe** [happybottoms/coverd#84]
In Products > Categories, try to delete "diapers" and you get a scary SQL error since that category is currently in use by "product."

![image](https://user-images.githubusercontent.com/1981351/72488824-b9a02d00-37d7-11ea-9ad3-916cc4c5af56.png)

We need to make nicer errors when this happens during a deletion.

**Comment by akoebbe** [comment]
Hmm... Do we have soft delete turned on for this entity? We shouldn't be doing an actual delete here.

**Comment by akoebbe** [comment]
Closed by #216
