### ISSUE TITLE
Partner Workflow

### ISSUE THREAD

**Issue by akoebbe** [happybottoms/coverd#87]
The Partner entity needs a status workflow. We can use the yohang/Finite library since some of us are familiar with it. But I'm open to other libraries.

Here is a screenshot of the transitions currently being used in Drupal...

<img width="1574" alt="Screen Shot 2020-01-15 at 10 16 30 PM" src="https://user-images.githubusercontent.com/1044465/72492935-b5c6d780-37e4-11ea-950c-05cc53542b69.png">

We can make the permissions portion another ticket if that makes more sense.

**Comment by ericpoe** [comment]
I'd like to explore using [`symfony/workflow`](https://symfony.com/doc/4.3/components/workflow.html) for this. I'll report back.

**Comment by akoebbe** [comment]
Good call. I forgot Symfony has one now.

**Comment by ericpoe** [comment]
What I have so far for the workflow. Circles are states, squares are transitions. Autogenerated via `bin/console workflow:dump partner_management | dot -Tpng -o graph.png`
![graph](https://user-images.githubusercontent.com/1981351/73142750-e36b1680-4057-11ea-8f87-625291a213af.png)

**Comment by akoebbe** [comment]
@ericpoe  Thank you! That graph looks pretty accurate to me. Nice little feature there.
